#!/bin/bash

set -xe

cat ./current-app-info/current-app.txt

sed "s/APPNAME/$(cat ./current-app-info/next-app.txt)-$APP_SUFFIX/" ./spring-hello-world/manifest.yml > ./app-manifest-output/manifest.yml

cat ./app-manifest-output/manifest.yml
