#!/bin/bash

set -xe

apt-get update
apt-get install wget -y
wget https://cli.run.pivotal.io/stable?release=debian64&source=github
dpkg -i path/to/cf-cli-*.deb && apt-get install -f


apt-get update
apt-get install openjdk-8-jdk -y
apt-get install maven -y
apt-get install cf-cli -y

cd spring-hello-world/hellospring
mvn clean package
cp manifest.yml ../spring-hello-world

