---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: spring-hello-world 

run:
  path: spring-hello-world/ci/tasks/maven-build
