---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "xenial"


inputs:
- name: spring-hello-world 

run:
  path: spring-hello-world/ci/tasks/maven-build
