#!/bin/bash

set -xe

apt-get install wget
wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key |  apt-key add -
echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list

apt-get update
apt-get install openjdk-8-jdk -y
apt-get install maven -y
apt-get install cf-cli -y

cd spring-hello-world/hellospring
mvn clean package
cp manifest.yml ../spring-hello-world

