---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: library/centos
    tag: "centos7"

inputs:
- name: spring-hello-world

run:
  path: spring-hello-world/ci/tasks/run-unit-tests
