---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos/python-35-centos7
    tag: "latest"

inputs:
- name: spring-hello-world

run:
  path: spring-hello-world/ci/tasks/run-unit-tests
