#!/bin/bash

set -xe

pwd
env

cf api $API --skip-ssl-validation

cf login -u "$CF_USER" -p "$CF_PWD" -o "$ORG" -s "$SPACE"

cf apps

cf routes


echo "Mapping green to prod route"
set +e
cf map-route hellospring-green local.pcfdev.io --hostname hellospring-prod
set -e

echo "Removing blue route from prod"
set +e
cf unmap-route hellospring-blue local.pcfdev.io --hostname hellospring-prod
set -e

echo "Removing green route from devtest"
set +e
cf unmap-route hellospring-green local.pcfdev.io --hostname hellospring-devtest
set -e

echo "Routes updated"

cf routes
