groups:
- name: main
  jobs:
  - maven-build-and-deploy
  - unit-tests
  - push-release-to-prod

resources:
- name: spring-hello-world
  type: git
  source:
    branch: master
    uri: https://github.com/mblakeashley/spring-hello-world.git

jobs:
- name: maven-build-and-deploy
  serial: true
  public: true
  plan:
  - get: spring-hello-world
    trigger: true
  - task: maven-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "xenial"

      inputs: 
      - name: spring-hello-world
      outputs:
      - name: builds

      run:
        path: spring-hello-world/ci/tasks/maven-build

  - task: deploy-maven-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalservices/docker-concourse-cf-tools
          tag: "latest"
      
      params:
        APP_SUFFIX: {{app-suffix}}
        APP_DOMAIN: {{app-domain}}
        API: {{api}}
        ORG: {{organization}}
        CF_USER: {{deploy-username}}
        CF_PWD: {{deploy-password}}
        SPACE: {{space}}
      
      inputs:
      - name: spring-hello-world
      - name: builds
      
      run:
        path: spring-hello-world/ci/tasks/deploy-release
        
     
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: spring-hello-world
    trigger: true
    passed:
      - maven-build-and-deploy
  - task: run-unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: centos/python-35-centos7
          tag: "latest"

      inputs:
      - name: spring-hello-world

      run:
        path: spring-hello-world/ci/tasks/run-unit-tests

- name: push-release-to-prod
  serial: true
  public: true
  plan:
  - get: spring-hello-world 
    trigger: true
    passed: 
      - unit-tests
  - task: switch-app-routes
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalservices/docker-concourse-cf-tools
          tag: "latest"

      params:
        APP_SUFFIX: {{app-suffix}}
        APP_DOMAIN: {{app-domain}}
        API: {{api}}
        ORG: {{organization}}
        CF_USER: {{deploy-username}}
        CF_PWD: {{deploy-password}}
        SPACE: {{space}}

      inputs:
      - name: spring-hello-world

      run:
        path: spring-hello-world/ci/tasks/update-routes
